### ISSUE TITLE
蓝牙pan未连接

### ISSUE THREAD

**Issue by Lewin671** [Orange367/DeskMini#1]
和你一样的配置，蓝牙也可以使用，但是在系统设置那里显示蓝牙pan未连接。
![image](https://user-images.githubusercontent.com/37481138/80048220-239c4100-8542-11ea-8cbb-d376b4312159.png)

**Comment by Orange367** [comment]
Hi Lewin671,

Thx for reaching out, I don't speak any Chinese so I will respond in English.

I don't use the Bluetooth PAN option so I never bothered to test it. Connecting to a personal hotspot on my iPhone works but that connection is setup via WiFi. 
You could delete the PAN option (-), then restart your system and add another Bluetooth PAN with (+) and see what happens. Because the Fenvi module uses Apple's native drivers I cannot provide any assistance in finding a solution.

**Comment by Lewin671** [comment]
Hi, Orange367,
    Thank you very much, and thanks for your good EFI.
    I try to use the method you mention above, but it doesn't work. Fortunately, the bluetooth's functions still work well. So, I can ignore this problem.
